// Generated by CoffeeScript 1.10.0
module.exports = {
  'uglify': false,
  'recursive': true,
  'preserve': false,
  'dirCache': true,
  'preventGlobalLeaks': true,
  'compileCoffeeChildren': false,
  'conditions': []
};
