// Generated by CoffeeScript 1.10.0
var regEx;

regEx = {
  fileExt: /.+\.(js|coffee)$/i,
  fileContent: /^(\s*)((?:\w|\W)+)/,
  escapedNewLine: /\\\n/g,
  backTicks: /`/g,
  preEscapedBackTicks: /\\`/g,
  "import": /^(?:(.*)([ \t\r]+)\W?|\W?)import\s+(?:\[(.+)\])?\s*(?:(?:([^\*,\{\s]+),? ?)?(\* as \S+|\{.+\})? from)?\s*(\S+?)(\).*?|\s*?)$/gm,
  "export": /^export\s+(?:(\{.+\})|(default|function\*?|class|var|const|let)\s+(\S+)?)?(.*)$/gm,
  commonJS: {
    "export": /^(.+[ \t\r]|.+\;|)(?:exports\s*|(?:module(?:\.exports|\['exports'\]|\["exports"\])\s*))(\[|[=\.])(.*)$/gm,
    "import": /^(.+[ \t\r]|.+\;|)require(?:\s+|\()\s*(".*?"|'.*?')(?:\)|[^\n\S]?)(.*)$/gm
  },
  comment: {
    singleLine: /([^:]|^)\/\/(.*)$/mg,
    multiLine: /(^|[^\\])(\/\*([\s\S]*?)\*\/)/mg
  },
  AMD: /(?:^\uFEFF?|[^$_a-zA-Z\xA0-\uFFFF.])define\s*\(\s*("[^"]+"\s*,\s*|'[^']+'\s*,\s*)?\s*(\[(\s*(("[^"]+"|'[^']+')\s*,|\/\/.*\r?\n|\/\*(.|\s)*?\*\/))*(\s*("[^"]+"|'[^']+')\s*,?)?(\s*(\/\/.*\r?\n|\/\*(.|\s)*?\*\/))*\s*\]|function\s*|{|[_$a-zA-Z\xA0-\uFFFF][_$a-zA-Z0-9\xA0-\uFFFF]*\))/
};

module.exports = regEx;
