module.exports = 
	dedupe: true
	usePaths: false
	sourceMap: null
	debug: false
	ignoreGlobals: false
	ignoreMissing: false
	ignoreErrors: false
	ignoreSyntaxErrors: false
	transform: []
	globalTransform: []
	ignoreTransform: []
	ignoreFile: []
	excludeFile: []
	specific: {}
	umd: ''
	returnLoader: false
