module.exports = 
	'recursive': true
	'preserve': false
	'dirCache': true
	'preventGlobalLeaks': true
	'includePathComments': true
	'compileCoffeeChildren': false
	'conditions': []
	'transform': []
	'globalTransform': []
	'fileSpecific': {}
