module.exports = 
	dedupe: true
	usePaths: false
	sourceMap: null
	debug: false
	extractDefaults: true
	bundleExternal: true
	ignoreGlobals: false
	ignoreMissing: false
	ignoreErrors: false
	ignoreSyntaxErrors: false
	matchAllConditions: false
	includeVersions: false
	inlineMap: true
	transform: []
	globalTransform: []
	finalTransform: []
	ignoreTransform: []
	ignoreFile: []
	excludeFile: []
	specific: {}
	placeholder: {}
	env: undefined
	loaderName: 'require'
	target: 'browser'
	umd: ''
	returnLoader: false
	returnExports: false
	noPkgConfig: false
	indent: false
